# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='image-link-here', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='style',
            field=models.CharField(default='style-link-here', max_length=500),
            preserve_default=False,
        ),
    ]
